In [25]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
MP_df = pd.read_csv('3DSC_MP.csv', skiprows=1)
MP_df.head()

formula_sc  formula_similarity  totreldiff  formula_frac  \
0  Ag0.02Ge2Pd1.98Sr1                   2    0.008000           1.0   
1     Ag0.15Sn0.85Te1                   3    0.150000           1.0   
2    Ag0.1Ge2Pd1.9Sr1                   2    0.040000           1.0   
3       Ag0.1In0.9Te1                   3    0.100000           1.0   
4       Ag0.2Ba1Si1.8                   3    0.133333           4.0   

   correct_formula_frac           formula_2 orig_formula_cif    tc sc_class  \
0                  True  Ag0.02Ge2Pd1.98Sr1        Ge2Pd2Sr1  2.64    Other   
1                  True     Ag0.15Sn0.85Te1           Sn1Te1  2.15    Other   
2                  True    Ag0.1Ge2Pd1.9Sr1        Ge2Pd2Sr1  2.62    Other   
3                  True       Ag0.1In0.9Te1           In1Te1  1.20    Other   
4                 False       Ag0.8Ba4Si7.2           Ba4Si8  3.20    Other   

   sc_class_unique_sc  ... monoclinic orthorhombic  tetragonal triclinic  \
0                True  ...          0            0           7         0   
1                True  ...          0            0           0         0   
2                True  ...          0            0           7         0   
3                True  ...          0            0           0         0   
4                True  ...          0            0           0         0   

  trigonal primitive base-centered body-centered face-centered weight  
0        0         0             0             1             0    1.0  
1        0         0             0             0             1    1.0  
2        0         0             0             1             0    1.0  
3        0         0             0             0             1    1.0  
4        0         1             0             0             0    1.0  

[5 rows x 92 columns]

In [3]:
MP_df.columns

Index(['formula_sc', 'formula_similarity', 'totreldiff', 'formula_frac',
       'correct_formula_frac', 'formula_2', 'orig_formula_cif', 'tc',
       'sc_class', 'sc_class_unique_sc', 'norm_formula_sc',
       'chemical_composition_sc', 'num_elements_sc', 'origin_sc',
       'old_formula_sc', 'database_id_2', 'original_formula_2',
       'chemical_composition_2', 'norm_formula_2', 'spacegroup_2',
       'crystal_system_2', 'lata_2', 'latb_2', 'latc_2', 'cif',
       'original_cif_2', 'material_id_2', 'band_gap_2', 'band_structure_2',
       'created_at_2', 'density_2', 'doi_2', 'doi_bibtex_2', 'dos_2',
       'e_above_hull_2', 'efermi_2', 'encut_2', 'energy_2',
       'energy_per_atom_2', 'exp_2', 'final_energy_2',
       'final_energy_per_atom_2', 'formation_energy_per_atom_2', 'has_2',
       'has_bandstructure_2', 'icsd_ids_2', 'is_ordered_2', 'last_updated_2',
       'magnetic_type_2', 'nsites_2', 'ntask_ids_2', 'original_task_id_2',
       'oxide_type_2', 'pretty_formula_2', 'pseu

In [4]:
MP_df['cif'] = MP_df['cif'].str.replace('data/final/MP/', '')
MP_df['cif'].head()

0    cifs/Ag0.02Ge2Pd1.98Sr1-MP-mp-978986-synth_dop...
1      cifs/Ag0.15Sn0.85Te1-MP-mp-1883-synth_doped.cif
2    cifs/Ag0.1Ge2Pd1.9Sr1-MP-mp-978986-synth_doped...
3        cifs/Ag0.1In0.9Te1-MP-mp-2597-synth_doped.cif
4        cifs/Ag0.2Ba1Si1.8-MP-mp-7275-synth_doped.cif
Name: cif, dtype: object

In [5]:
MP_df['cif'][0]

'cifs/Ag0.02Ge2Pd1.98Sr1-MP-mp-978986-synth_doped.cif'

In [6]:
row_1 = MP_df.iloc[0]
print(row_1)

formula_sc              Ag0.02Ge2Pd1.98Sr1
formula_similarity                       2
totreldiff                           0.008
formula_frac                           1.0
correct_formula_frac                  True
                               ...        
primitive                                0
base-centered                            0
body-centered                            1
face-centered                            0
weight                                 1.0
Name: 0, Length: 92, dtype: object


In [24]:
print(row_1["lata_2"])

4.438671999438209


In [31]:
from pymatgen.io.cif import CifParser
import numpy as np

# Specify the path to your CIF file
cif_path = MP_df['cif'][0]

# Create a CIF parser and parse the CIF file
parser = CifParser(cif_path)
structure = parser.parse_structures(primitive=True)[0]

# Print information about the crystal structure
print("Lattice Parameters:")
print("a =", structure.lattice.a)
print("b =", structure.lattice.b)
print("c =", structure.lattice.c)
print("alpha =", structure.lattice.alpha)
print("beta =", structure.lattice.beta)
print("gamma =", structure.lattice.gamma)
print()

print("Space Group:", structure.get_space_group_info())
print()

thing = [] 

print("Atomic Positions:")
for site in structure.sites:
    print(f"{site.species}: {site.frac_coords}")
    thing.append([site.frac_coords[0], site.frac_coords[1], site.frac_coords[2]])
    thing.append([-site.frac_coords[0], -site.frac_coords[1], -site.frac_coords[2]])

thing = np.array(thing)

Lattice Parameters:
a = 4.438672
b = 4.438672
c = 6.030548339846585
alpha = 111.59328751266106
beta = 111.5932875163173
gamma = 90.00000001

Space Group: ('I4/mmm', 139)

Atomic Positions:
Sr1: [0. 0. 0.]
Ge1: [0.37057 0.37057 0.74114]
Ge1: [0.62943 0.62943 0.25886]
Pd0.99 Ag0.01: [0.75 0.25 0.5 ]
Pd0.99 Ag0.01: [0.25 0.75 0.5 ]


I have above the asymmetric unit, the symmetry operation is then applied along all three axes. This would then pack the unit cell and make the percieved unit cell we need.

In [37]:
import plotly.graph_objects as go

def plotting_struct(structure):
    x, y, z = structure[:,0] , structure[:,1], structure[:,2]
    fig = go.Figure(data=[go.Scatter3d(
        x = x,
        y = y,
        z = z,
        mode='markers',
        marker=dict(
            size=5,
            opacity=0.8
        )
    )])
    
    fig.update_layout(
        scene=dict(
            xaxis=dict(title='X'),
            yaxis=dict(title='Y'),
            zaxis=dict(title='Z')
        )
    )
    fig.show()


In [39]:
from pymatgen.io.cif import CifParser

# Specify the path to your CIF file
cif_path = MP_df['cif'][0]

# Create a CIF parser and parse the CIF file
parser = CifParser(cif_path)
structure = parser.parse_structures(primitive=True)[0]

# Generate the packed structure
packed_structure = structure.pack()

# Print or do whatever you want with the packed structure
print(packed_structure)


AttributeError: 'Structure' object has no attribute 'pack'

In [43]:
from pymatgen.core import Lattice, Structure

BaTiO3=Structure.from_file(MP_df['cif'][0])
print(BaTiO3.get_space_group_info())
BaTiO3=BaTiO3*(2,2,2)
print(BaTiO3)
print(BaTiO3.get_space_group_info())

('I4/mmm', 139)
Full Formula (Sr8 Ag0.16 Ge16 Pd15.84)
Reduced Formula: Sr8Ag0.16Ge16Pd15.84
abc   :   8.877344   8.877344  12.061097
angles: 111.593288 111.593288  90.000000
pbc   :       True       True       True
Sites (40)
  #  SP                         a         b        c
---  ------------------  --------  --------  -------
  0  Sr                  0         0         0
  1  Sr                  0         0         0.5
  2  Sr                  0         0.5       1
  3  Sr                  0         0.5       0.5
  4  Sr                  0.5       0         0
  5  Sr                  0.5       0         0.5
  6  Sr                  0.5       0.5       0
  7  Sr                  0.5       0.5       0.5
  8  Ge                  0.185285  0.185285  0.37057
  9  Ge                  0.185285  0.185285  0.87057
 10  Ge                  0.185285  0.685285  0.37057
 11  Ge                  0.185285  0.685285  0.87057
 12  Ge                  0.685285  0.185285  0.37057
 13  Ge           

In [44]:
BaTiO3.sites

[PeriodicSite: Sr0 (Sr) (0.0, 0.0, 0.0) [0.0, 0.0, 0.0],
 PeriodicSite: Sr0 (Sr) (0.0, 0.0, 6.031) [0.0, 0.0, 0.5],
 PeriodicSite: Sr0 (Sr) (-0.6465, 4.076, 10.43) [2.577e-18, 0.5, 1.0],
 PeriodicSite: Sr0 (Sr) (-0.6465, 4.076, 4.397) [2.577e-18, 0.5, 0.5],
 PeriodicSite: Sr0 (Sr) (4.127, 0.0, -1.634) [0.5, 0.0, 1.193e-17],
 PeriodicSite: Sr0 (Sr) (4.127, 0.0, 4.397) [0.5, 0.0, 0.5],
 PeriodicSite: Sr0 (Sr) (3.481, 4.076, -3.267) [0.5, 0.5, 2.386e-17],
 PeriodicSite: Sr0 (Sr) (3.481, 4.076, 2.764) [0.5, 0.5, 0.5],
 PeriodicSite: Ge1 (Ge) (1.29, 1.511, 3.259) [0.1853, 0.1853, 0.3706],
 PeriodicSite: Ge1 (Ge) (1.29, 1.511, 9.289) [0.1853, 0.1853, 0.8706],
 PeriodicSite: Ge1 (Ge) (0.6433, 5.587, 1.625) [0.1853, 0.6853, 0.3706],
 PeriodicSite: Ge1 (Ge) (0.6433, 5.587, 7.656) [0.1853, 0.6853, 0.8706],
 PeriodicSite: Ge1 (Ge) (5.417, 1.511, 1.625) [0.6853, 0.1853, 0.3706],
 PeriodicSite: Ge1 (Ge) (5.417, 1.511, 7.656) [0.6853, 0.1853, 0.8706],
 PeriodicSite: Ge1 (Ge) (4.77, 5.587, -0.008173)

In [47]:
print("Atomic Positions:")
thing = []
for site in BaTiO3.sites:
    thing.append([site.frac_coords[0], site.frac_coords[1], site.frac_coords[2]])
    thing.append([-site.frac_coords[0], -site.frac_coords[1], -site.frac_coords[2]])
    
thing = np.array(thing)
print(thing)

Atomic Positions:
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  5.00000000e-01]
 [-0.00000000e+00 -0.00000000e+00 -5.00000000e-01]
 [ 2.57735510e-18  5.00000000e-01  1.00000000e+00]
 [-2.57735510e-18 -5.00000000e-01 -1.00000000e+00]
 [ 2.57735510e-18  5.00000000e-01  5.00000000e-01]
 [-2.57735510e-18 -5.00000000e-01 -5.00000000e-01]
 [ 5.00000000e-01  0.00000000e+00  1.19278320e-17]
 [-5.00000000e-01 -0.00000000e+00 -1.19278320e-17]
 [ 5.00000000e-01  0.00000000e+00  5.00000000e-01]
 [-5.00000000e-01 -0.00000000e+00 -5.00000000e-01]
 [ 5.00000000e-01  5.00000000e-01  2.38556641e-17]
 [-5.00000000e-01 -5.00000000e-01 -2.38556641e-17]
 [ 5.00000000e-01  5.00000000e-01  5.00000000e-01]
 [-5.00000000e-01 -5.00000000e-01 -5.00000000e-01]
 [ 1.85285000e-01  1.85285000e-01  3.70570000e-01]
 [-1.85285000e-01 -1.85285000e-01 -3.70570000e-01]
 [ 1.85285000e-01  1.85285000e-01  8.70570000e-01]
 [-1.85285000

In [48]:
plotting_struct(thing)

In [50]:
# Create a CIF parser and parse the CIF file
parser = CifParser(MP_df['cif'][0])

structure = parser.parse_structures(primitive=True)[0]

unit_cell = structure.make_supercell([2, 2, 2])

unit_cell_coordinates = unit_cell.cart_coords
plotting_struct(unit_cell_coordinates)