In [3]:
import sys
sys.path.append('..')
from cleaned_code import *

import warnings
warnings.filterwarnings("ignore")

In [4]:
import pandas as pd
import numpy as np
import pickle

# Featurise Data

In [5]:
with open('featurised_datasets/asymcell.pkl', 'rb') as f:
    assymcell = pickle.load(f)
    
with open('featurised_datasets/unitcell.pkl', 'rb') as f:
    unitcell = pickle.load(f)

In [6]:
print(len(assymcell))

print(assymcell[1])

5773
[[0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [7.34948192e-16 5.55748767e+00 1.14006969e-15]]


In [7]:
print(len(unitcell))

print(unitcell[1])

5773
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.61982481e+00  3.70499178e+00 -8.46261429e-17]
 [ 1.30991241e+00  3.70499178e+00 -2.26883484e+00]
 [-1.30991241e+00  7.40998356e+00 -2.26883484e+00]
 [ 1.30991241e+00  3.70499178e+00  2.26883484e+00]
 [-1.30991241e+00  7.40998356e+00  2.26883484e+00]
 [ 2.61982481e+00  7.40998356e+00  1.33226763e-15]
 [ 7.34948192e-16  1.11149753e+01  8.88178420e-16]
 [ 8.80377684e-16  5.55748767e+00  1.01412405e-15]
 [-2.61982481e+00  9.26247945e+00  1.01412405e-15]
 [ 1.30991241e+00  9.26247945e+00 -2.26883484e+00]
 [-1.30991241e+00  1.29674712e+01 -2.26883484e+00]
 [ 1.30991241e+00  9.26247945e+00  2.26883484e+00]
 [-1.30991241e+00  1.29674712e+01  2.26883484e+00]
 [ 2.61982481e+00  1.29674712e+01  2.22044605e-15]
 [ 2.05161435e-15  1.66724630e+01  1.77635684e-15]]


Just checking we have the right data and the right length of data

In [8]:
features = PresistentHomologyFeatures(coords=assymcell)
asym_topol_feat_mat, asym_topol_feat_list = features.featurising_coords()

In [9]:
np.save("featurised_datasets\PHF_AsymCell", asym_topol_feat_mat)